### ISSUE TITLE
Questões de usabilidade da widget @binaryimage

### ISSUE THREAD

**Issue by afmfe-iul** [andre-santos-pt/pandionj#16]
Algumas questões em relação a esta widget estão um pouco contra intuitivas:

- os valores da matriz de booleans a `true `correspondem à cor preta e os `false` à cor branca

- o eixo do "x" corresponde à primeira dimensão da matriz e varia na vertical de cima para baixo, e o eixo do "y" corresponde à segunda dimensão da matriz e varia na horizontal da esquerda para a direita

- como já tinhamos falado, a border de raiz da widget causa um efeito estranho especialmente quando se usa o método drawBorder() sugerido nos exercícios

**Comment by andre-santos-pt** [comment]
- mudei a binaryimage para true=branco, false=preto

- o segundo ponto não está certo. neste momento, new int[10][5] corresponde a uma imagem com 10 pixels de altura e 5 de largura. a primeira dimensão corresponde ao eixo do y, e a segunda ao x. isto é o normal em processamento de imagem.

- retirei o contorno das imagens (todos os tipos)
