### ISSUE TITLE
Ctrl-y é o atalho para fazer Redo definido pelo eclipse

### ISSUE THREAD

**Issue by afmfe-iul** [andre-santos-pt/pandionj#3]
Talvez seja melhor optar por um atalho que ainda não esteja em uso por definição no eclipse

**Comment by afmfe-iul** [comment]
Ctrl-U parece ser uma boa alternativa, acho que não é usado por default

**Comment by andre-santos-pt** [comment]
ok, alterei para CTRL-U, "U" de último :)

**Comment by afmfe-iul** [comment]
Boa mnemônica, não tinha pensado nela! Veio a calhar :)
