### ISSUE TITLE
Possível falha de deteção de Gatherer

### ISSUE THREAD

**Issue by afmfe-iul** [andre-santos-pt/pandionj#4]
![missed_gatherer](https://user-images.githubusercontent.com/10389190/30482320-6de4aca4-9a1a-11e7-93ee-9d11bf79210c.PNG)

Neste caso a variável `result `não é identificada como Gatherer. Segundo o que li no pseudo código para detetar um Gatherer (na tese do Hugo), hasConditionalAssignment neste caso devia ser true.

Para rectificar testei a outra maneira de uma variável ser considerada um Gatherer (novamente segundo o pseudo código do Hugo, quando assignmentFromOtherVar = true), e parece que tudo funcionou como esperado.

![detected_gatherer](https://user-images.githubusercontent.com/10389190/30482564-7ba949ac-9a1b-11e7-995b-70a7a0aa0f57.PNG)

(`sum` foi detetado como Gatherer correctamente)

**Comment by andre-santos-pt** [comment]
a variável result está a ser detetada como Stepper (mais particularmente, um contador), não deve ser um Gatherer (imaginando a anotação das parcelas, seria pouco útil, porque seria sempre algo tipo 1+1+1+1+...)

**Comment by afmfe-iul** [comment]
Pela análise do Hugo acho que há uma especificação dos papeis diferente. 
O Stepper (iterador?) sofre um incremento sequencial (não depende de outras variáveis, nem invocações de métodos) e incondicional em todas as iterações do ciclo. 
O Contador é uma especificação do Gatherer (diferem porque o counter só regista incrementos de 1), e os "reassignments" de um contador dentro do ciclo são condicionais. O que ele fez nas ilustrações dele foi não mostrar a anotação das parcelas para o counter!

**Comment by andre-santos-pt** [comment]
sim, o Contador era distinguido, mas não tinha nenhuma ilustração particular. o que temos agora é a setinha para cima (incrementador).

**Comment by afmfe-iul** [comment]
Ok ok, parece-me intuitivo!
