### ISSUE TITLE
Cannot complete the install because some dependencies are not satisfiable

### ISSUE THREAD

**Issue by Roukaysa** [andre-santos-pt/pandionj#44]
Estou a rodar Kubuntu 19.04 e não obtive sucesso a instalar o plugin enquanto que obtive sucesso instantâneo através do Windows 10.

Testei 3 versões diferentes do Eclipse:
- 2018-06 ([a recomendada no site](http://pandionj.iscte-iul.pt/installation.html))
- 2019-03
- 2019-06

De todas as vezes foi me dado o seguinte erro:
> Cannot complete the install because some dependencies are not satisfiable
  org.eclipse.equinox.p2.iu; pt.iscte.pandionj.feature.feature.group [0.4.0,0.4.0] cannot be installed in this environment because its filter is not applicable.

[Screenshot do erro](https://i.imgur.com/GAWyBzS.png)

Não sei se vale a pena realçar mas eis as specs do PC: 
Lenovo IdeaPad 330s
Intel Core i3-8130U
Intel UHD Graphics 620
4GB RAM DDR4 2400MHz
SSD 128GB

Edit:
Testei numa Virtual Machine, noutro PC, Kubuntu e Manjaro. O mesmo erro ocorre.

**Comment by andre-santos-pt** [comment]
fixed
