### ISSUE TITLE
Permitir criação de vectores dentro das caixas de diálogo para inserção de argumentos

### ISSUE THREAD

**Issue by afmfe-iul** [andre-santos-pt/pandionj#6]
Estive a testar a aula dos vetores e do ponto de vista de utilizador senti bastante falta desta feature! Mas não sei se se enquadra no plano

**Comment by andre-santos-pt** [comment]
isto até seria fácil de fazer, mas a ideia é aquela expressão corresponder a código Java válido (e colocar {. ,  .} não o seria)

**Comment by andre-santos-pt** [comment]
acrescentei suporte para vetores na invocação, tipo func({1,2,3}), embora isto não seja sintaxe válida de java. comecei também a fazer para matrizes (qq({{1,2},{3,4}})), mas por uma limitação do instrumentador de código não é possível injetar o código correto de invocação.
