### ISSUE TITLE
Bounds dos iteradores da 2ª dimensão das matrizes estão a aparecer na 1ª dimensão

### ISSUE THREAD

**Issue by afmfe-iul** [andre-santos-pt/pandionj#8]
![matrixes](https://user-images.githubusercontent.com/10389190/30512725-6243e882-9aed-11e7-8a6e-3538cb2c3f45.PNG)

**Comment by andre-santos-pt** [comment]
para já a solução para este bug foi martelada, por forma a que estas vars só sejam mostradas para a 1ª dimensão

**Comment by andre-santos-pt** [comment]
fixed
